namespace: databases-dev
service:
  type: NodePort
  nodePort: 30432
resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
persistence:
  size: 5Gi
auth:
  username: devuser
  password: devpass
  database: devdb
